import jsPDF from 'jspdf';
import 'jspdf-autotable';

declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: any) => jsPDF;
  }
}

interface UserData {
  uid?: string;
  email?: string;
  displayName?: string;
  premiumPlan?: string;
  premiumExpiresAt?: string;
}

interface ExportDataOptions {
  user: UserData | null;
  displayName: string;
  isPremium: boolean;
}

export const exportStudyDataToPDF = ({ user, displayName, isPremium }: ExportDataOptions) => {
  try {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(20);
    doc.setTextColor(111, 66, 193); // Purple color
    doc.text('Study Tracker Pro - Data Export', 20, 20);
    
    // User info
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text(`Generated for: ${displayName || user?.email || 'User'}`, 20, 35);
    doc.text(`Export Date: ${new Date().toLocaleDateString()}`, 20, 45);
    doc.text(`Account Email: ${user?.email || 'N/A'}`, 20, 55);
    
    // Premium status
    doc.setFontSize(12);
    doc.text(`Premium Status: ${isPremium ? 'Active' : 'Free'}`, 20, 70);
    if (isPremium) {
      doc.text(`Premium Plan: ${user?.premiumPlan || 'N/A'}`, 20, 80);
      doc.text(`Premium Expires: ${user?.premiumExpiresAt ? new Date(user.premiumExpiresAt).toLocaleDateString() : 'N/A'}`, 20, 90);
    }
    
    // Sample study data (in a real app, this would come from Firebase)
    const studyData = [
      ['Date', 'Subject', 'Duration (min)', 'Sessions', 'Score'],
      ['2024-01-15', 'Mathematics', '120', '2', '85%'],
      ['2024-01-14', 'Physics', '90', '1', '92%'],
      ['2024-01-13', 'Chemistry', '150', '3', '78%'],
      ['2024-01-12', 'Mathematics', '60', '1', '88%'],
      ['2024-01-11', 'English', '45', '1', '95%'],
    ];
    
    // Study sessions table
    doc.setFontSize(16);
    doc.text('Recent Study Sessions', 20, isPremium ? 105 : 85);
    
    doc.autoTable({
      head: [studyData[0]],
      body: studyData.slice(1),
      startY: isPremium ? 115 : 95,
      theme: 'grid',
      headStyles: {
        fillColor: [111, 66, 193],
        textColor: [255, 255, 255],
        fontStyle: 'bold'
      },
      alternateRowStyles: {
        fillColor: [249, 250, 251]
      },
      margin: { left: 20, right: 20 }
    });
    
    // Statistics summary
    const finalY = (doc as any).lastAutoTable.finalY + 20;
    doc.setFontSize(16);
    doc.text('Study Statistics Summary', 20, finalY);
    
    const statsY = finalY + 15;
    doc.setFontSize(12);
    doc.text('• Total Study Hours: 7.75 hours', 30, statsY);
    doc.text('• Total Sessions: 8 sessions', 30, statsY + 10);
    doc.text('• Average Score: 87.6%', 30, statsY + 20);
    doc.text('• Most Studied Subject: Mathematics', 30, statsY + 30);
    doc.text('• Study Streak: 5 days', 30, statsY + 40);
    
    // Footer
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(10);
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by Study Tracker Pro - Your Smart Study Companion', 20, pageHeight - 20);
    doc.text('For support, visit our Telegram channels or contact us directly.', 20, pageHeight - 10);
    
    // Save the PDF
    doc.save(`StudyTracker_DataExport_${new Date().toISOString().split('T')[0]}.pdf`);
    
    return true;
  } catch (error) {
    console.error('Error generating PDF:', error);
    throw new Error('Failed to generate PDF. Please try again.');
  }
};
